import path from "node:path";

export const SUPPORTED_LANGUAGES = [
  "arduino",
  "bash",
  "c",
  "c_sharp",
  "clojure",
  "commonlisp",
  "cpp",
  "css",
  "d",
  "dart",
  "elisp",
  "elixir",
  "elm",
  "fortran",
  "gleam",
  "go",
  "haskell",
  "hcl",
  "html",
  "java",
  "javascript",
  "json",
  "julia",
  "kotlin",
  "lua",
  "matlab",
  "objc",
  "ocaml",
  "ocaml_interface",
  "php",
  "pony",
  "python",
  "ql",
  "r",
  "racket",
  "ruby",
  "rust",
  "scala",
  "solidity",
  "swift",
  "toml",
  "tsx",
  "typescript",
  "yaml",
  "zig",
] as const;

export type SupportedLanguage = (typeof SUPPORTED_LANGUAGES)[number];

const EXTENSION_MAP: Record<string, SupportedLanguage> = {
  ".py": "python",
  ".js": "javascript",
  ".mjs": "javascript",
  ".cjs": "javascript",
  ".jsx": "javascript",
  ".ts": "typescript",
  ".tsx": "tsx",
  ".go": "go",
  ".rs": "rust",
  ".java": "java",
  ".c": "c",
  ".h": "c",
  ".cpp": "cpp",
  ".cc": "cpp",
  ".cxx": "cpp",
  ".hpp": "cpp",
  ".hxx": "cpp",
  ".cs": "c_sharp",
  ".rb": "ruby",
  ".php": "php",
  ".swift": "swift",
  ".kt": "kotlin",
  ".kts": "kotlin",
  ".scala": "scala",
  ".sc": "scala",
  ".dart": "dart",
  ".lua": "lua",
  ".sh": "bash",
  ".bash": "bash",
  ".zsh": "bash",
  ".el": "elisp",
  ".ex": "elixir",
  ".exs": "elixir",
  ".elm": "elm",
  ".ml": "ocaml",
  ".mli": "ocaml_interface",
  ".m": "objc",
  ".zig": "zig",
  ".ql": "ql",
  ".sol": "solidity",
  ".html": "html",
  ".css": "css",
  ".json": "json",
  ".yaml": "yaml",
  ".yml": "yaml",
  ".toml": "toml",
  ".r": "r",
  ".R": "r",
  ".jl": "julia",
  ".hs": "haskell",
  ".d": "d",
  ".clj": "clojure",
  ".cljs": "clojure",
  ".cljc": "clojure",
  ".rkt": "racket",
  ".f90": "fortran",
  ".f95": "fortran",
  ".f03": "fortran",
  ".f08": "fortran",
  ".gleam": "gleam",
  ".hcl": "hcl",
  ".tf": "hcl",
  ".tfvars": "hcl",
  ".ino": "arduino",
  ".pony": "pony",
  ".lisp": "commonlisp",
  ".cl": "commonlisp",
  ".mat": "matlab",
};

export function filenameToLang(filename: string): SupportedLanguage | null {
  const ext = path.extname(filename).toLowerCase();
  return EXTENSION_MAP[ext] ?? null;
}

export function isSupportedFile(filename: string): boolean {
  return filenameToLang(filename) !== null;
}
